name: Publish Python distributions to TestPyPI

on:
  push:
#    branches:
#      - develop
#      - release/**
    tags:
      - v*rc
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-n-publish-pre-release:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pypa/build
        run: python -m pip install build wheel pbr twine --user
      - name: Build a binary wheel and a source tarball
        run: python setup.py bdist_wheel sdist
        env:
          PBR_VERSION: ${{ github.ref_name }}
      - name: Publish distribution to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.CYTHONPACKAGE_TEST_PYPI_API_TOKEN }}
        run: |
          twine upload -r testpypi dist/*
