name: Publish Python distributions to PyPI

on:
  push:
#    branches:
#      - master
    tags:
      - v[012].[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-n-publish-release:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pypa/build
        run: python -m pip install build wheel pbr twine --user
      - name: Build a binary wheel and a source tarball
        run: python setup.py bdist_wheel sdist
        env:
          PBR_VERSION: ${{ github.ref_name }}
      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.CYTHONPACKAGE_PYPI_API_TOKEN }}
        run: |
          twine upload dist/*